
services:
  network-deploy-service:
    networks:
      - chandooiitm

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      - SPRING_PROFILE_ACTIVE: qa
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
